name: test & build
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

permissions:
  contents: read
  packages: write

jobs:
  quality:
    name: Lint / TypeCheck / Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run Lint/Typecheck/Test
        run: bun ci

  ci:
    uses: tyreesamurai/ci-cd/.github/workflows/build-and-push.yml@main
    needs: quality
